### ISSUE TITLE
Does java-grok support "name capture only"?

### ISSUE THREAD

**Issue by lephix** [thekrakken/java-grok#39]
I didn't find this feature in this library. Could you figure it out for me ?

**Comment by palmerabollo** [comment]
+1, this would be useful. Any plans to include it in java-grok?

**Comment by anthonycorbacho** [comment]
Hi, sadly i dont have time to implement more feature.
If someone can create a PR, I will gladly review and merge it.

**Comment by trixpan** [comment]
@lephix @palmerabollo - mind explaining what do you mean by "name capture only"? Happy to have a go in trying to address it.

Cheers

**Comment by palmerabollo** [comment]
@trixpan It means to capture named expressions only or not (i.e. %{IP:ip} but not ${IP}). It's a quite common option (see for example https://grokdebug.herokuapp.com/) because in many occasions you don't want to get all the intermediate expressions a grok match contains.

The good part is that I think it was fixed in this PR https://github.com/thekrakken/java-grok/pull/45/files

**Comment by trixpan** [comment]
@palmerabollo so this can be closed?

**Comment by palmerabollo** [comment]
Yes, I think so.

**Comment by fbacchella** [comment]
But if fails in some case, see issue #61.

**Comment by retoo** [comment]
I created a PR https://github.com/thekrakken/java-grok/pull/70 which should improve the situation described by @fbacchella

**Comment by retoo** [comment]
#70  is merged, the discussed problems should be fixed.
